# https://taskfile.dev

version: '3'

tasks:
  test:
    cmds:
      - go test -race -p=1 ./... -v
      - golangci-lint run ./...

  fmt:
    cmds:
      - golangci-lint fmt

  all:
    deps:
      - fmt
      - test
